'''
Created on Sep 3, 2014

@author: RakeshSingh
'''
s="TATCACCAAGACGTGCTCGTAGTTTTAGGCTCGATGCTACGCCAATACGCAGACCTGTAGGGCTGTGACAGTGCCTATAATCACAACCAGTCAACATAGGCGGAGTGGATATACTGTACGGCAATCTAAAACGACATAGAGTTTGGACTCGCAGGTGAGAACAGACTAAGAACTGCTTCAGGGCACTAAGCGAGGAATCTCTATCGGGGTGGCCCAACCAGGTTAAGCCTTGATTAATAATCACCCCAAAGACACAGAGGACCATAAGGTATGTTTTAGTAATTGTAGCCGGCCATTCTGAAACTCGGACGGTTTACGCACCAGTTGGCTGATAGTACACCGTGCGGTTGCCCTAGTTCTCTAACCTTATACCACAACACTACCAGACCGATTCCGAGGGGCTGAGAAAAGGACGCCATCACTAGGGGCTTAGGTTCAGCCCGAACATTGTCTGCTTCCCGTCAGCTACGGCCGTCCGGTTTTACCCCGGGTAACTCTGGGGCTTGTACAAACATAGTACGCCAATGTTCACGTGCACTTGCAGTCGTGAAGGCACGATAATCGTAGTTAGTCTCTCGTCGTAGAGTCCACCACGATGTAGTCTTCGCCTTAGAGCTGTCTGTCGTGATCAGATTCGTAATGGATACGAGGGGCCAGCGTTCCATAGTAGACCTAGGTAAAAGTGCGAATGTAACACGTTGATGCATAATATGAGACACCGCCATTAGCACGATCCTCGCGATGATCAAAACTCCGCTTTCCACAATGAGCAGGTAGGAGTGCAAACGCACGTGACGATGCCGGTAGCGGGCCATTGTCGATTCTGGACTGGAAAG"

k=p=i=j=0

for n in s:
    if n is 'A':
        k +=1
    elif n is 'C':
        p +=1
    elif n is 'G':
        i +=1
    else:
        j +=1
    
print '%d %d %d %d' %(k,p,i,j)
